name: run

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install requests

      - run: python filter.py

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: sub-result
          path: mci_best.txt
