name: build-sub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run filter
        run: python filter.py

      # 🔥 مهم: commit + push درست
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add mci_best.txt

          git commit -m "update sub" || echo "no changes"

          git pull --rebase origin main || true

          git push
